include: [docker-compose.yaml]
services:
  minio:
    command: server --console-address=":9001"
    container_name: clearml-minio
    image: dhi.io/minio:0-debian-dev
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-}
    restart: unless-stopped
    volumes:
      - /opt/clearml/data/minio:/data
    ports:
      - "9001:9001"
